PROMPT CREATE OR REPLACE PROCEDURE prc_deleta_solsaipro_n_atend
CREATE OR REPLACE PROCEDURE prc_deleta_solsaipro_n_atend IS

  -- Cursor que verifica as solicitações para exclusão
  Cursor Cr_Solicitacao Is
    SELECT SOLSAI_PRO.CD_SOLSAI_PRO
          ,ITSOLSAI_PRO.CD_ITSOLSAI_PRO
      FROM SOLSAI_PRO
      LEFT JOIN ITSOLSAI_PRO
        ON SOLSAI_PRO.CD_SOLSAI_PRO = ITSOLSAI_PRO.CD_SOLSAI_PRO
      WHERE HR_SOLSAI_PRO < SYSDATE - 2
        AND TP_SITUACAO = 'P'
      ;

BEGIN
  FOR rg1 in Cr_Solicitacao LOOP
  --Excluir solicitação
  DELETE FROM DBAMV.ITSOLSAI_PRO_FECHAMENTO WHERE CD_ITSOLSAI_PRO = RG1.CD_ITSOLSAI_PRO;
  DELETE FROM DBAMV.ITSOLSAI_PRO_STATUS 	WHERE CD_ITSOLSAI_PRO = RG1.CD_ITSOLSAI_PRO;
  DELETE FROM DBAMV.CONTROLE_ITEM_SOLICITACAO WHERE CD_ITSOLSAI_PRO = RG1.CD_ITSOLSAI_PRO;
  COMMIT;
  END LOOP;


  FOR rg2 in Cr_Solicitacao LOOP
  --Excluir solicitação
  DELETE FROM DBAMV.CONTROLE_SOLICITACAO WHERE CD_SOLSAI_PRO = RG2.CD_SOLSAI_PRO;
  DELETE FROM DBAMV.MOVIMENTACAO_RESERVA_PRODUTO WHERE CD_SOLSAI_PRO = RG2.CD_SOLSAI_PRO;
  DELETE FROM DBAMV.ITSOLSAI_PRO  WHERE CD_SOLSAI_PRO = RG2.CD_SOLSAI_PRO;
  DELETE FROM DBAMV.SOLSAI_PRO    WHERE CD_SOLSAI_PRO = RG2.CD_SOLSAI_PRO;
  COMMIT;
  END LOOP;
END;
/

