SELECT * 
  FROM ATENDIME
  JOIN CARTEIRA
    ON ATENDIME.CD_PACIENTE = CARTEIRA.CD_PACIENTE
   AND ATENDIME.NR_CARTEIRA = CARTEIRA.NR_CARTEIRA
   AND ATENDIME.CD_CON_PLA = CARTEIRA.CD_CON_PLA
   AND ATENDIME.CD_CONVENIO = CARTEIRA.CD_CONVENIO
  WHERE ATENDIME.CD_CONVENIO = 480
    AND DT_ATENDIMENTO = '17/11/2022'
    AND CARTEIRA.CD_CATEGORIA_PLANO IS NULL