SELECT ATENDIME.CD_ATENDIMENTO 
      ,PACIENTE.NM_PACIENTE
      ,ESPECIALID.DS_ESPECIALID
      ,PRESTADOR.NM_PRESTADOR 
      ,SETOR.NM_SETOR
      ,Decode(ATENDIME.TP_ATENDIMENTO,'I','INTERNADO','U','URGÊNCIA','A','AMBULATÓRIO','E','EXTERNO') TP_ATENDIMENTO
      ,TIP_PRESC.DS_TIP_PRESC
      , CASE Trunc((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)))))))
             WHEN 0 THEN CASE Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))
                            WHEN 0 THEN Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minutos'
                            WHEN 1 THEN Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))||' Hora '||
                                        Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minutos'
                            ELSE   Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))||' Horas e '||
                                   Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minuto(s)'
                            END
             WHEN 1 THEN CASE Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))
                            WHEN 0 THEN Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minutos'
                            WHEN 1 THEN Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))||' Hora e '||
                                        Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minutos'
                            ELSE   Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))||' Horas '||
                                   Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minutos'
                            END
             
             ELSE Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))))),24)) || ' Dias ' ||
                  Trunc(Mod((((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO))) * 1440)/60),24))||' Horas e '||
                  Trunc(Mod(((to_number(SYSDATE - FNC_MV_RECUPERA_DATA_HORA(DT_ATENDIMENTO, HR_ATENDIMENTO)) * 1440)),60))||' Minutos'
             END tempo_internacao

  FROM DBAMV.PRE_MED
  JOIN DBAMV.ATENDIME
    ON PRE_MED.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
  JOIN DBAMV.PACIENTE
    ON PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE
  JOIN DBAMV.ITPRE_MED
    ON PRE_MED.CD_PRE_MED = ITPRE_MED.CD_PRE_MED
  left JOIN DBAMV.SETOR
    ON PRE_MED.CD_SETOR = SETOR.CD_SETOR
  JOIN DBAMV.TIP_PRESC
    ON ITPRE_MED.CD_TIP_PRESC = TIP_PRESC.CD_TIP_PRESC
  JOIN DBAMV.ESPECIALID
    ON ATENDIME.CD_ESPECIALID = ESPECIALID.CD_ESPECIALID
  JOIN DBAMV.PRESTADOR
    ON PRE_MED.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR 
  WHERE TIP_PRESC.CD_TIP_ESQ = 'DIE'
    AND DT_ALTA IS NULL 
    AND (ATENDIME.TP_ATENDIMENTO IN ('A','U','E') AND DT_ATENDIMENTO > SYSDATE - 2 OR TP_ATENDIMENTO = 'I')
ORDER BY 1 DESC 





