SELECT ESTOQUE.CD_ESTOQUE
      ,ESTOQUE.DS_ESTOQUE
      ,COTA_SETOR.CD_ESTOQUE
      ,PRODUTO.CD_PRODUTO 
      ,PRODUTO.DS_PRODUTO
      ,COTA_SETOR.QT_COTA
      ,UNI_PRO.CD_UNIDADE
      ,EST_PRO.QT_ESTOQUE_ATUAL
      ,COTA_SETOR.QT_COTA - EST_PRO.QT_ESTOQUE_ATUAL DIFERENCA
      
  FROM DBAMV.COTA_SETOR
  JOIN DBAMV.UNI_PRO
    ON COTA_SETOR.CD_UNI_PRO = UNI_PRO.CD_UNI_PRO
   AND COTA_SETOR.CD_PRODUTO = UNI_PRO.CD_PRODUTO
  JOIN DBAMV.ESTOQUE
    ON COTA_SETOR.CD_SETOR = ESTOQUE.CD_SETOR
  JOIN DBAMV.EST_PRO                                                                   
    ON ESTOQUE.CD_ESTOQUE = EST_PRO.CD_ESTOQUE
   AND COTA_SETOR.CD_PRODUTO = EST_PRO.CD_PRODUTO
  JOIN DBAMV.PRODUTO
    ON PRODUTO.CD_PRODUTO = EST_PRO.CD_PRODUTO 
   AND PRODUTO.CD_PRODUTO = COTA_SETOR.CD_PRODUTO
  WHERE COTA_SETOR.QT_COTA <> EST_PRO.QT_ESTOQUE_ATUAL 
    AND ESTOQUE.CD_ESTOQUE = 64
ORDER BY 2
