SELECT ESPECIE.CD_ESPECIE
      ,ESPECIE.DS_ESPECIE
      ,CLASSE.CD_CLASSE 
      ,CLASSE.DS_CLASSE
      ,SUB_CLAS.CD_SUB_CLA
      ,SUB_CLAS.DS_SUB_CLA
      ,PRODUTO.CD_PRODUTO
      ,PRODUTO.DS_PRODUTO
  FROM DBAMV.ESPECIE
  JOIN DBAMV.CLASSE 
    ON ESPECIE.CD_ESPECIE = CLASSE.CD_ESPECIE
  JOIN DBAMV.SUB_CLAS
    ON ESPECIE.CD_ESPECIE = SUB_CLAS.CD_ESPECIE
   AND CLASSE.CD_CLASSE = SUB_CLAS.CD_CLASSE
  JOIN DBAMV.PRODUTO
    ON PRODUTO.CD_SUB_CLA = SUB_CLAS.CD_SUB_CLA
   AND PRODUTO.CD_CLASSE = CLASSE.CD_CLASSE
   AND PRODUTO.CD_ESPECIE = ESPECIE.CD_ESPECIE  
  WHERE SN_PROD_PERMANENTE = 'ME'
ORDER BY ESPECIE.CD_ESPECIE
        ,CLASSE.CD_CLASSE
        ,SUB_CLAS.CD_SUB_CLA
        ,PRODUTO.CD_PRODUTO
