SELECT ESPECIE.CD_ESPECIE
      ,ESPECIE.DS_ESPECIE
      ,CLASSE.CD_CLASSE
      ,CLASSE.DS_CLASSE
      ,SUB_CLAS.CD_SUB_CLA
      ,SUB_CLAS.DS_SUB_CLA
  FROM DBAMV.ESPECIE
  JOIN DBAMV.CLASSE
    ON ESPECIE.CD_ESPECIE = CLASSE.CD_ESPECIE
  JOIN DBAMV.SUB_CLAS
    ON ESPECIE.CD_ESPECIE = SUB_CLAS.CD_ESPECIE
   AND CLASSE.CD_CLASSE = SUB_CLAS.CD_CLASSE
ORDER BY ESPECIE.CD_ESPECIE
        ,CLASSE.CD_CLASSE
        ,SUB_CLAS.CD_SUB_CLA

