--PRODUTOS COM PRO_FAT SEM VINCULO NA TUSS
SELECT PRODUTO.CD_ESPECIE
      ,ESPECIE.DS_ESPECIE
      ,PRODUTO.CD_CLASSE
      ,CLASSE.DS_CLASSE
      ,PRODUTO.CD_SUB_CLA
      ,SUB_CLAS.DS_SUB_CLA
      ,PRODUTO.CD_PRODUTO
      ,PRODUTO.DS_PRODUTO
      ,PRODUTO.CD_PRO_FAT
  FROM DBAMV.PRODUTO
  JOIN DBAMV.ESPECIE
    ON PRODUTO.CD_ESPECIE = ESPECIE.CD_ESPECIE
  JOIN DBAMV.CLASSE
    ON PRODUTO.CD_CLASSE = CLASSE.CD_CLASSE
   AND PRODUTO.CD_ESPECIE = CLASSE.CD_ESPECIE
  JOIN DBAMV.SUB_CLAS
    ON PRODUTO.CD_SUB_CLA = SUB_CLAS.CD_SUB_CLA
   AND PRODUTO.CD_CLASSE = SUB_CLAS.CD_CLASSE
   AND PRODUTO.CD_ESPECIE = SUB_CLAS.CD_ESPECIE
  WHERE PRODUTO.CD_PRO_FAT NOT IN (SELECT TUSS.CD_PRO_FAT
                                    FROM DBAMV.TUSS
                                    WHERE TUSS.CD_PRO_FAT IS NOT NULL
                                  )
ORDER BY PRODUTO.CD_ESPECIE
        ,PRODUTO.CD_CLASSE
        ,PRODUTO.CD_SUB_CLA
        ,PRODUTO.CD_PRODUTO

-- PRODUTOS PRO_FAT VINCULADOS A TUSS
SELECT TUSS.CD_TIP_TUSS
      ,TUSS.CD_TUSS
      ,TUSS.DS_TUSS
      ,TUSS.CD_PRO_FAT
      ,TUSS.CD_CONVENIO
      ,CONVENIO.NM_CONVENIO
  FROM DBAMV.TUSS
  LEFT JOIN DBAMV.CONVENIO
    ON TUSS.CD_CONVENIO = CONVENIO.CD_CONVENIO
  WHERE TUSS.CD_TIP_TUSS IN (19,20,00)
    AND TUSS.CD_PRO_FAT IS NOT NULL
ORDER BY TUSS.CD_TIP_TUSS, TUSS.CD_PRO_FAT, CONVENIO.NM_CONVENIO