SELECT Decode(PRODUTO.CD_ESPECIE,1,'MED','MAT') MAT_MED
      ,PRODUTO.CD_PRODUTO
      ,PRODUTO.DS_PRODUTO
      ,TIP_PRESC.CD_TIP_PRESC
      ,TIP_PRESC.DS_TIP_PRESC
      ,PRODUTO.CD_PRO_FAT
      ,PRO_FAT.DS_PRO_FAT
      ,UNI_PRO.DS_UNIDADE
      ,ITUNIDADE.VL_FATOR
  FROM DBAMV.PRODUTO
  LEFT JOIN DBAMV.TIP_PRESC
    ON PRODUTO.CD_PRODUTO = TIP_PRESC.CD_PRODUTO
  LEFT JOIN DBAMV.PRO_FAT
    ON PRODUTO.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
  LEFT JOIN DBAMV.UNI_PRO
    ON PRODUTO.CD_PRODUTO = UNI_PRO.CD_PRODUTO
  LEFT JOIN DBAMV.ITUNIDADE
    ON UNI_PRO.CD_ITUNIDADE = ITUNIDADE.CD_ITUNIDADE
  WHERE PRODUTO.CD_ESPECIE IN (1,2)
    AND UNI_PRO.TP_RELATORIOS = 'R'
    AND TIP_PRESC.SN_ATIVO = 'S'


ORDER BY 1,2


           --SELECT * FROM UNI_PRO

           --SELECT * FROM itunidade