SELECT SOLSAI_PRO.CD_SOLSAI_PRO
      ,To_Char(SOLSAI_PRO.HR_SOLSAI_PRO,'DD/MM/YYYY') DT
      ,To_Char(SOLSAI_PRO.HR_SOLSAI_PRO,'HH24:MI')    HR
      ,SOLSAI_PRO.TP_ORIGEM_SOLICITACAO
      ,ESTOQUE.CD_ESTOQUE
  FROM DBAMV.SOLSAI_PRO
  JOIN DBAMV.ESTOQUE
    ON SOLSAI_PRO.CD_ESTOQUE = ESTOQUE.CD_ESTOQUE
  WHERE SOLSAI_PRO.CD_SOLSAI_PRO NOT IN (SELECT To_Number(VALOR)
                                          FROM DBAMV.IMP_PARAMETRO
                                          WHERE IMP_PARAMETRO.NOME = 'P_CD_SOLSAI_PRO'
                                            AND VALOR IS NOT NULL
                                        )
    AND Trunc(SOLSAI_PRO.DT_SOLSAI_PRO) >= '05/07/2023'
    --AND DT_IMPRESSAO IS NULL
    AND SOLSAI_PRO.TP_SOLSAI_PRO NOT IN ('S','D','C','E')
    AND SOLSAI_PRO.TP_SITUACAO = 'P'
    --AND SOLSAI_PRO.CD_ESTOQUE = 3
ORDER BY 1 DESC



------TP_SOLSAI_PRO-------
-- D DEVOLUÇÃO DE SETOR
-- C DEVOLUÇÃO DE PACIENTE
-- E PEDIDO PARA ESTOQUE
-- P PEDIDO DE PACIENTE
-- S PEDIDO DE SETOR



-----TP_SITUACAO
-- P PEDIDO
-- C ATENDIDO PARCIAL
-- A CANCELADO
-- S CONFIRMADO