SELECT ATENDIME.*
  FROM DBAMV.ATENDIME
  JOIN DBAMV.CARTEIRA
    ON ATENDIME.CD_PACIENTE = CARTEIRA.CD_PACIENTE
   AND ATENDIME.CD_CONVENIO = CARTEIRA.CD_CONVENIO 
  WHERE ATENDIME.CD_CONVENIO = 11   -- IPERGS
    AND CARTEIRA.CD_CATEGORIA_PLANO IS NULL 
