SELECT FRANQUIAS.DS_FRANQUIA
      ,FRANQUIAS.CD_CONVENIO 
      ,FRANQUIAS.TP_ATENDIMENTO
      ,FRANQUIAS.CD_PRO_FAT
      ,PRO_FAT.DS_PRO_FAT
      ,GRU_PRO.CD_GRU_PRO
      ,GRU_PRO.DS_GRU_PRO
      ,FRANQUIAS.VL_PERC_PARTICIP
      ,FRANQUIAS.VL_PARTICIP       
  FROM DBAMV.FRANQUIAS
  LEFT JOIN DBAMV.PRO_FAT
    ON FRANQUIAS.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
  LEFT JOIN DBAMV.GRU_PRO
    ON FRANQUIAS.CD_GRU_PRO = GRU_PRO.CD_GRU_PRO 
  WHERE cd_convenio = 480 
    AND cd_categoria_plano IS NULL