SELECT To_Char(REPLACE(REPLACE(PRODUTO.DS_ESPECIFICACAO,'REF:',''),' ','')) REF
      ,PRODUTO.CD_PRO_FAT
      ,LAB_PRO.CD_REGISTRO
      ,TUSS.CD_TUSS
      ,TUSS.DS_TUSS
      ,TUSS.CD_REF_FABRICANTE 
  FROM DBAMV.PRODUTO 
  JOIN DBAMV.LAB_PRO
    ON PRODUTO.CD_PRODUTO = LAB_PRO.CD_PRODUTO
  JOIN DBAMV.TUSS
    ON LAB_PRO.CD_REGISTRO  = TUSS.CD_REFERENCIA
  WHERE PRODUTO.CD_ESPECIE = 7
    AND PRODUTO.DS_ESPECIFICACAO IS NOT NULL
    --AND LAB_PRO.CD_REGISTRO = '80146501901'
    AND PRODUTO.CD_PRO_FAT NOT IN (SELECT CD_PRO_FAT FROM DBAMV.TUSS WHERE CD_PRO_FAT IS NOT NULL)
    AND To_Char(REPLACE(REPLACE(PRODUTO.DS_ESPECIFICACAO,'REF:',''),' ','')) = TUSS.CD_REF_FABRICANTE 
ORDER BY PRODUTO.CD_PRO_FAT
        ,TUSS.CD_REF_FABRICANTE
