PROMPT CREATE OR REPLACE PROCEDURE PRC_INS_NOVO_GRU_PRO
CREATE OR REPLACE PROCEDURE PRC_INS_NOVO_GRU_PRO
  (
  PCD_GRU_PRO_ANTIGO INTEGER,
  PCD_GRU_PRO_NOVO INTEGER
  )
IS
--
BEGIN
    --INSERT NA ACRESCIMOS E DESCONTOS DO CONVENIO
    INSERT INTO DBAMV.ACRESC_DESCONTOS
    SELECT PCD_GRU_PRO_NOVO
          ,ACRESC_DESCONTOS.CD_REGRA
          ,ACRESC_DESCONTOS.VL_PERC_ACRESCIMO
          ,ACRESC_DESCONTOS.VL_PERC_DESCONTO
          ,ACRESC_DESCONTOS.TP_ATEND_AMBULATORIAL
          ,ACRESC_DESCONTOS.TP_ATEND_EXTERNO
          ,ACRESC_DESCONTOS.TP_ATEND_INTERNACAO
          ,ACRESC_DESCONTOS.TP_ATEND_URGEME
          ,ACRESC_DESCONTOS.DS_DESCONTO
          ,ACRESC_DESCONTOS.DS_ACRESCIMO
          ,ACRESC_DESCONTOS.SN_VL_FILME
          ,ACRESC_DESCONTOS.SN_VL_OPERACIONAL
          ,ACRESC_DESCONTOS.SN_VL_HONORARIO
          ,ACRESC_DESCONTOS.TP_ATEND_HOMECARE
          ,ACRESC_DESCONTOS.SN_DESTACAR_NA_FATURA
          ,ACRESC_DESCONTOS.DT_INICIO_VIGENCIA
          ,ACRESC_DESCONTOS.DT_FINAL_VIGENCIA
  FROM DBAMV.ACRESC_DESCONTOS
  WHERE ACRESC_DESCONTOS.CD_GRU_PRO = PCD_GRU_PRO_ANTIGO
    AND (ACRESC_DESCONTOS.CD_REGRA,PCD_GRU_PRO_NOVO) NOT IN (SELECT CD_REGRA, CD_GRU_PRO FROM ACRESC_DESCONTOS);

  --INSERT NA TABELA DE TAXA EXTRA DO IPE
  INSERT INTO DBAMV.IT_TAXA_EXTRA_IPE
  SELECT IT_TAXA_EXTRA_IPE.CD_TAXA
        ,PCD_GRU_PRO_NOVO
        ,IT_TAXA_EXTRA_IPE.CD_PRO_FAT
    FROM DBAMV.IT_TAXA_EXTRA_IPE
    WHERE IT_TAXA_EXTRA_IPE.CD_GRU_PRO = PCD_GRU_PRO_ANTIGO
      AND (PCD_GRU_PRO_NOVO,IT_TAXA_EXTRA_IPE.CD_TAXA) NOT IN (SELECT CD_GRU_PRO, CD_TAXA FROM IT_TAXA_EXTRA_IPE);

  --INSERT NA TABELA DE FORMA DE APRESENTACAO
  INSERT INTO DBAMV.ITFOR_APRE_GRU_PRO
  SELECT PCD_GRU_PRO_NOVO
        ,ITFOR_APRE_GRU_PRO.CD_FOR_APRE
        ,PCD_GRU_PRO_NOVO
        ,PCD_GRU_PRO_NOVO
        ,ITFOR_APRE_GRU_PRO.TP_DATA
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_CH
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_SIMPRO
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_BRASINDICE
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_UNIDADE
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_PERC_PAGO
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_PERC_PROC
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_PRESTADOR
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_HE
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_FP
        ,ITFOR_APRE_GRU_PRO.TP_IMP_ACRESC_DESC
        ,ITFOR_APRE_GRU_PRO.SN_SEPARADA
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_VL_FILME
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_CBHPM
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_DIFEP
        ,ITFOR_APRE_GRU_PRO.SN_IMPRIME_TODAS_DATAS
    FROM DBAMV.ITFOR_APRE_GRU_PRO
    WHERE ITFOR_APRE_GRU_PRO.CD_GRU_PRO = PCD_GRU_PRO_ANTIGO
      AND (ITFOR_APRE_GRU_PRO.CD_FOR_APRE,PCD_GRU_PRO_NOVO) NOT IN (SELECT CD_FOR_APRE, CD_GRU_PRO FROM DBAMV.ITFOR_APRE_GRU_PRO);

  --INSERT DO GRUPO NA REGRA
  INSERT INTO DBAMV.ITREGRA
  SELECT ITREGRA.CD_REGRA
      ,ITREGRA.CD_TAB_FAT
      ,PCD_GRU_PRO_NOVO
      ,ITREGRA.VL_PERCETUAL_PAGO
      ,ITREGRA.TP_HOR_ESP_SD
      ,ITREGRA.CD_HORARIO
      ,ITREGRA.TP_VALOR_BASE
      ,ITREGRA.CD_CONTRATO
  FROM DBAMV.ITREGRA
  WHERE ITREGRA.CD_GRU_PRO = PCD_GRU_PRO_ANTIGO
    AND (ITREGRA.CD_REGRA, PCD_GRU_PRO_NOVO) NOT IN (SELECT CD_REGRA, CD_GRU_PRO FROM DBAMV.ITREGRA);

  --INSERT NA TABELA DE FRANQUIA
  INSERT INTO DBAMV.FRANQUIAS
  SELECT SEQ_FRANQUIAS.NEXTVAL
      ,FRANQUIAS.DS_FRANQUIA
      ,FRANQUIAS.CD_CON_PLA
      ,FRANQUIAS.CD_CONVENIO
      ,FRANQUIAS.CD_CATEGORIA_PLANO
      ,FRANQUIAS.TP_ATENDIMENTO
      ,FRANQUIAS.SN_TITULAR
      ,FRANQUIAS.CD_PRO_FAT
      ,PCD_GRU_PRO_NOVO
      ,FRANQUIAS.VL_PERC_PARTICIP
      ,FRANQUIAS.VL_PARTICIP
      ,FRANQUIAS.QT_PONTOS
      ,FRANQUIAS.SN_PENSIONISTA
  FROM DBAMV.FRANQUIAS
  WHERE FRANQUIAS.CD_GRU_PRO = PCD_GRU_PRO_ANTIGO
    AND FRANQUIAS.CD_PRO_FAT IS NULL
    AND (PCD_GRU_PRO_NOVO,FRANQUIAS.CD_CON_PLA,FRANQUIAS.CD_CONVENIO,FRANQUIAS.CD_CATEGORIA_PLANO,FRANQUIAS.TP_ATENDIMENTO) NOT IN (SELECT FRANQUIAS.CD_GRU_PRO
                                                                                                                                          ,FRANQUIAS.CD_CON_PLA
                                                                                                                                          ,FRANQUIAS.CD_CONVENIO
                                                                                                                                          ,FRANQUIAS.CD_CATEGORIA_PLANO
                                                                                                                                          ,FRANQUIAS.TP_ATENDIMENTO
                                                                                                                                      FROM DBAMV.FRANQUIAS
                                                                                                                                      WHERE FRANQUIAS.CD_PRO_FAT IS NULL);


END;
/

GRANT EXECUTE ON PRC_INS_NOVO_GRU_PRO TO dbaps;
GRANT EXECUTE ON PRC_INS_NOVO_GRU_PRO TO dbasgu;
GRANT EXECUTE ON PRC_INS_NOVO_GRU_PRO TO mv2000;
GRANT EXECUTE ON PRC_INS_NOVO_GRU_PRO TO mvintegra;












