/*
            INFORMAR OS USUARIOS NOS 2 BLOCOS PARA O CASO DE LIBERAR O SETOR DA UNIDADE DE INTERNACAO
                               BLOCO 1 LIBERA AS UNIDADES DE INTERNAÇÃO DO USUARIO MODELO
                               BLOCO 2 LIBERA OS SETORES DO USUARIO MODELO
*/
--INSERT INTO DBAMV.USUARIO_UNID_INT
SELECT B.CD_UNID_INT
      ,A.CD_USUARIO
      ,B.CD_SETOR
      ,B.SN_SOLICITACAO_PRODUTO_SETOR
      ,B.SN_SOLICITACAO_PRODUTO_GAS_SAL
      ,B.SN_SOLICITACAO_PRODUTO_PACIENT
      ,B.SN_SOLICITACAO_PRODUTO_ESTOQ
      ,B.SN_SOLICITACAO_PRODUTO_EMP
      ,B.SN_MOVIMENTACAO_SETOR
      ,B.SN_MOVIMENTACAO_GASTO_SALA
      ,B.SN_MOVIMENTACAO_PACIENTE
      ,B.SN_MOVIMENTACAO_ESTOQUE
      ,B.SN_MOVIMENTACAO_EMPRESA
      ,B.SN_CONFIRMACAO_RECEBIMENTO
  FROM (SELECT CD_USUARIO
          FROM DBASGU.USUARIOS
          WHERE USUARIOS.CD_USUARIO IN ('HC6641')--USUARIOS PARA INSERIR
        )A
        ,(SELECT *
            FROM DBAMV.USUARIO_UNID_INT
            WHERE USUARIO_UNID_INT.CD_ID_USUARIO = 'HC5130' --USUARIO MODELO
              AND USUARIO_UNID_INT.CD_UNID_INT IS NOT NULL
        )B
WHERE (B.CD_UNID_INT,B.CD_SETOR,A.CD_USUARIO) NOT IN (SELECT CD_UNID_INT,CD_SETOR,CD_ID_USUARIO FROM USUARIO_UNID_INT WHERE CD_UNID_INT IS NOT NULL) -- nao insere estoque que ja tem
UNION
SELECT B.CD_UNID_INT
      ,A.CD_USUARIO
      ,B.CD_SETOR
      ,B.SN_SOLICITACAO_PRODUTO_SETOR
      ,B.SN_SOLICITACAO_PRODUTO_GAS_SAL
      ,B.SN_SOLICITACAO_PRODUTO_PACIENT
      ,B.SN_SOLICITACAO_PRODUTO_ESTOQ
      ,B.SN_SOLICITACAO_PRODUTO_EMP
      ,B.SN_MOVIMENTACAO_SETOR
      ,B.SN_MOVIMENTACAO_GASTO_SALA
      ,B.SN_MOVIMENTACAO_PACIENTE
      ,B.SN_MOVIMENTACAO_ESTOQUE
      ,B.SN_MOVIMENTACAO_EMPRESA
      ,B.SN_CONFIRMACAO_RECEBIMENTO
  FROM (SELECT CD_USUARIO
          FROM DBASGU.USUARIOS
          WHERE USUARIOS.CD_USUARIO IN ('HC6641')--USUARIOS PARA INSERIR
        )A
        ,(SELECT *
            FROM DBAMV.USUARIO_UNID_INT
            WHERE USUARIO_UNID_INT.CD_ID_USUARIO = 'HC5130' --USUARIO MODELO
              AND USUARIO_UNID_INT.CD_UNID_INT IS NULL
        )B
WHERE (B.CD_SETOR,A.CD_USUARIO) NOT IN (SELECT CD_SETOR,CD_ID_USUARIO FROM USUARIO_UNID_INT WHERE CD_UNID_INT IS NULL) -- nao insere estoque que ja tem

