--INSERT INTO DBASGU.PAPEL_USUARIOS
SELECT A.CD_USUARIO
      ,B.CD_PAPEL
      ,B.TP_PAPEL
      ,B.SN_USUARIO_MASTER
  FROM (SELECT CD_USUARIO
          FROM DBASGU.USUARIOS
          WHERE USUARIOS.CD_USUARIO IN ('HC4399','HC5656','HC4501')--USUARIOS PARA INSERIR
        )A
        ,(SELECT *
            FROM DBASGU.PAPEL_USUARIOS
            WHERE cd_usuario = 'HC5130' --USUARIO MODELO
        )B
WHERE (B.CD_PAPEL ,A.CD_USUARIO) NOT IN (SELECT CD_PAPEL, CD_USUARIO FROM DBASGU.PAPEL_USUARIOS) -- nao insere papel que ja tem


