SELECT * 
  FROM(
       SELECT 
              PRE_MED.CD_PRE_MED,
              ATENDIME.CD_ATENDIMENTO,
              ATENDIME.CD_PACIENTE,
              NM_PACIENTE,
              TO_CHAR(DT_NASCIMENTO, 'DD/MM/RRRR') DT_NASC,
              ATENDIME.CD_LEITO,
              DS_LEITO,
              NVL(DS_UNID_INT,NM_SETOR) SETORES,
              TO_CHAR(HR_PRE_MED, 'DD/MM/RRRR') DT_PRESC,
              ITPRE_MED.CD_TIP_ESQ,
              DS_TIP_ESQ,
              DS_TIP_PRESC,
              DS_ITPRE_MED
         FROM ATENDIME
         JOIN PACIENTE ON ATENDIME.CD_PACIENTE  = PACIENTE.CD_PACIENTE
         JOIN PRE_MED ON PRE_MED.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
         JOIN ITPRE_MED ON PRE_MED.CD_PRE_MED = ITPRE_MED.CD_PRE_MED
         JOIN TIP_ESQ ON ITPRE_MED.CD_TIP_ESQ = TIP_ESQ.CD_TIP_ESQ
         JOIN TIP_PRESC ON ITPRE_MED.CD_TIP_PRESC = TIP_PRESC.CD_TIP_PRESC
         JOIN ORI_ATE ON ATENDIME.CD_ORI_ATE = ORI_ATE.CD_ORI_ATE
         JOIN SETOR ON ORI_ATE.CD_SETOR = SETOR.CD_SETOR
         LEFT JOIN LEITO ON ATENDIME.CD_LEITO = LEITO.CD_LEITO
         LEFT JOIN UNID_INT ON LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
        WHERE NM_PACIENTE = '{V_CD_PACIENTE}'
          AND ITPRE_MED.CD_TIP_ESQ = 'DIE'
 AND atendime.dt_alta is null
        ORDER BY 1 DESC
      ) WHERE ROWNUM = 1