SELECT LISTAGG(a.DS_DESJEJUM) 
       WITHIN GROUP(ORDER BY a.DS_DESJEJUM DESC)DS_DESJEJUM
      ,LISTAGG(a.DS_COLACAO) 
       WITHIN GROUP(ORDER BY a.DS_COLACAO DESC) DS_COLACAO    
      ,LISTAGG(a.DS_ALMOCO) 
       WITHIN GROUP(ORDER BY a.DS_ALMOCO DESC)  DS_ALMOCO
      ,LISTAGG(a.DS_LANCHE) 
       WITHIN GROUP(ORDER BY a.DS_LANCHE DESC)  DS_LANCHE
      ,LISTAGG(a.DS_JANTAR) 
       WITHIN GROUP(ORDER BY a.DS_JANTAR DESC)  DS_JANTAR
      ,LISTAGG(a.DS_CEIA) 
       WITHIN GROUP(ORDER BY a.DS_CEIA DESC)    DS_CEIA
      ,LISTAGG(a.DS_OBS) 
       WITHIN GROUP(ORDER BY a.DS_OBS DESC)     DS_OBS
      ,CD_UNID_INT
      ,DS_UNID_INT
      ,CD_PACIENTE
      ,NM_PACIENTE
      ,DT_ATENDIMENTO
      ,CD_ATENDIMENTO
      ,NR_IDADE
      ,DS_CID
      ,DS_RESUMO
      ,Decode(SN_ACOMPANHANTE,'N','Não Possui Acompanhante','S','Possui Acompanhante') SN_ACOMPANHANTE
      ,DTHR_INTERNACAO
      ,OBS_MED
      ,DS_TIPO_DIETA
FROM (
      Select LEITO.CD_UNID_INT                    CD_UNID_INT
            ,UNID_INT.DS_UNID_INT                 DS_UNID_INT
            ,PACIENTE.CD_PACIENTE                 CD_PACIENTE
            ,PACIENTE.NM_PACIENTE                 NM_PACIENTE
            ,ATENDIME.DT_ATENDIMENTO              DT_ATENDIMENTO
            ,ATENDIME.CD_ATENDIMENTO              CD_ATENDIMENTO
            ,PACK_INTERNAMENTO.RETORNA_IDADE(PACIENTE.DT_NASCIMENTO,SysDate)  NR_IDADE
            ,CID.DS_CID                           DS_CID
            ,LEITO.DS_RESUMO                      DS_RESUMO
            ,ATENDIME.SN_ACOMPANHANTE             SN_ACOMPANHANTE
            ,fnc_mv_recupera_data_hora(ATENDIME.DT_ATENDIMENTO,ATENDIME.HR_ATENDIMENTO) DTHR_INTERNACAO
            ,TIPO_DIETA.DS_TIPO_DIETA             DS_TIPO_DIETA
            ,ITPRE_MED.DS_ITPRE_MED               OBS_MED
            ,TIPO_REFEICAO.DS_TIPO_REFEICAO       DS_TIPO_REFEICAO
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '1' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- DESJEJUM
              ELSE NULL 
              END DS_DESJEJUM
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '2' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- COLACAO
              ELSE NULL 
              END DS_COLACAO
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '3' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- ALMOCO
              ELSE NULL 
              END DS_ALMOCO
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '4' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- LANCHE
              ELSE NULL 
              END DS_LANCHE
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '5' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- JANTAR
              ELSE NULL 
              END DS_JANTAR
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '6' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- CEIA
              ELSE NULL 
              END DS_CEIA
            ,CASE (TIPO_REFEICAO.CD_TIPO_REFEICAO)
              WHEN '16' THEN FICHA_NUTRICAO.DS_OBSERVACAO -- OBS
              ELSE NULL 
              END DS_OBS


        FROM DBAMV.ATENDIME
        JOIN DBAMV.PACIENTE
          ON ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
        LEFT JOIN DBAMV.CID
          ON ATENDIME.CD_CID = CID.CD_CID
        LEFT JOIN DBAMV.LEITO
          ON ATENDIME.CD_LEITO = LEITO.CD_LEITO
        LEFT JOIN DBAMV.UNID_INT
          ON LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
        LEFT JOIN DBAMV.FICHA_NUTRICAO
          ON ATENDIME.CD_ATENDIMENTO = FICHA_NUTRICAO.CD_ATENDIMENTO
        JOIN (SELECT Max(ITPRE_MED.CD_ITPRE_MED) CD_ITPRE_MED
                    ,PRE_MED.CD_ATENDIMENTO
                FROM PRE_MED
                JOIN ITPRE_MED 
                  ON PRE_MED.CD_PRE_MED = ITPRE_MED.CD_PRE_MED
                WHERE ITPRE_MED.CD_TIP_ESQ = 'DIE'
              GROUP BY PRE_MED.CD_ATENDIMENTO
              ) MAXDIETA
          ON ATENDIME.CD_ATENDIMENTO = MAXDIETA.CD_ATENDIMENTO
        JOIN DBAMV.ITPRE_MED
          ON ITPRE_MED.CD_ITPRE_MED = MAXDIETA.CD_ITPRE_MED
        JOIN DBAMV.TIP_PRESC
          ON TIP_PRESC.CD_TIP_PRESC = ITPRE_MED.CD_TIP_PRESC
        left JOIN DBAMV.TIPO_DIETA
          ON TIP_PRESC.CD_TIPO_DIETA = TIPO_DIETA.CD_TIPO_DIETA
        left JOIN DBAMV.TIPO_REFEICAO
          ON FICHA_NUTRICAO.CD_TIPO_REFEICAO = TIPO_REFEICAO.CD_TIPO_REFEICAO
        WHERE ATENDIME.TP_ATENDIMENTO = 'I'
          AND ATENDIME.DT_ALTA IS NULL   
          AND ATENDIME.CD_ATENDIMENTO = 11862
      ORDER BY ATENDIME.CD_ATENDIMENTO
              ,TIPO_REFEICAO.CD_TIPO_REFEICAO
     )A
GROUP BY  CD_UNID_INT
      ,DS_UNID_INT
      ,CD_PACIENTE
      ,NM_PACIENTE
      ,DT_ATENDIMENTO
      ,CD_ATENDIMENTO
      ,NR_IDADE
      ,DS_CID
      ,DS_RESUMO
      ,SN_ACOMPANHANTE
      ,DTHR_INTERNACAO
      ,OBS_MED
      ,DS_TIPO_DIETA
