-- 01/03/2007 Carlos André
   -- Alteração do grant para leitura da v$session em procedure do dbamv e dbasgu
   -- Alteração para dá permissão de geração de trace para dbamv e dbasgu em banco 9i e 10g

-- 01/03/2007 Carlos André
   -- Alteração do grant para leitura da v$session em procedure do dbamv e dbasgu
   -- Alteração para dá permissão de geração de trace para dbamv e dbasgu em banco 9i e 10g
-- 06/12/2007 Marrone
   -- Alteracao para dar Grant Merge Any View para o MV2000.
-- 29/12/2008 Marrone
   -- Alteracao para dar Grant de Execute em DBMS_AQ.
-- 26/09/2015 Marcos Macedo
   -- Alteracao para grants que permitem criação de usuário pelo Soul  
-- 21/10/2015 Marcos Macedo
   -- Alteracao para permissao do AUTHID CURRENT_USER para execucao dos usuarios system e sys
-- 10/06/2016 Marcos Macedo
   -- Permissoes para DBAMV e DBASGU
-- 13/09/2016 Marcos Macedo
   -- Permissao SELECT no objeto DBA_SYS_PRIVS para a role MV2000
  
   
   
   -- Para esta ação é necessário se conectar com o usuário SYS
-- connect sys/change_on_install;
-- /
GRANT SELECT ON SYS.OBJ$ TO MV2000
/
GRANT SELECT ON SYS.OBJ$ TO DBAMV,DBASGU,MVINTEGRA
/
GRANT SELECT ON SYS.TRIGGER$ TO MV2000
/
GRANT SELECT ON SYS.USER$ TO MV2000
/
GRANT SELECT ON SYS.USER$ TO DBAMV,DBASGU,MVINTEGRA
/
GRANT SELECT ON V_$SESSION TO MV2000
/
GRANT SELECT ON SYS.V_$PROCESS TO MV2000
/
GRANT SELECT ON SYS.V_$INSTANCE TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON SYS.V_$INSTANCE TO MV2000
/
GRANT SELECT ON SYS.GV_$INSTANCE TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON SYS.GV_$INSTANCE TO MV2000
/
GRANT SELECT ON SYS.V_$PROCESS TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON SYS.V_$PROCESS TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON V_$SESSION TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON GV_$SESSION TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON GV_$SESSION TO MV2000
/
GRANT SELECT ON GV_$LOCK TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON GV_$LOCK TO MV2000
/
GRANT SELECT ON GV_$SESSION TO MV2000
/
GRANT SELECT ON GV_$SESSION TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON DBA_ROLE_PRIVS TO MV2000
/
GRANT SELECT ON DBA_SYS_PRIVS TO MV2000
/
GRANT SELECT ON SYS.V_$MYSTAT TO MV2000
/
GRANT SELECT ON SYS.GV_$MYSTAT TO DBASGU,DBAMV,MVINTEGRA
/
GRANT SELECT ON V_$MYSTAT TO DBAMV
/
 GRANT SELECT ON V_$SQL TO DBAMV
/
 GRANT SELECT ON GV_$SQL TO DBAMV
/
GRANT SELECT ON GV_$PROCESS TO MV2000
/
GRANT SELECT ON GV_$PARAMETER TO MV2000
/


-- REFERENTE AO TISS
GRANT ALTER ANY INDEX TO DBAMV,DBASGU,MVINTEGRA
/
GRANT ALTER ANY INDEXTYPE TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT CREATE ANY TABLE TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT CREATE TABLE TO DBAMV,DBASGU,MVINTEGRA
/
GRANT DROP ANY TABLE TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT DROP ANY SEQUENCE TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT CREATE ANY SEQUENCE TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT CREATE PUBLIC SYNONYM TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT DROP  PUBLIC SYNONYM TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT CREATE ANY VIEW TO DBAMV ,DBASGU,MVINTEGRA
/
GRANT CREATE VIEW TO DBAMV,DBASGU,MVINTEGRA
/

-- PERMISSAO PARA ELIMITAR SESSOES INATIVAS
GRANT SELECT ON DBA_OBJECTS TO DBAMV
/
GRANT SELECT ON DBA_JOBS TO DBAMV,MVINTEGRA
/
GRANT SELECT ON DBA_JOBS TO MV2000
/
GRANT SELECT ON DBA_JOBS_RUNNING TO MV2000
/

-- PERMISSÕES PARA O MVEDI ( MVINTEGRA E DBAMV ) 

GRANT EXECUTE ON SYS.DBMS_SQL TO DBAMV
/
GRANT EXECUTE ON SYS.DBMS_SQL TO MVINTEGRA
/
GRANT ALTER ANY PROCEDURE TO DBAMV
/
GRANT ALTER ANY TRIGGER TO DBAMV
/
GRANT CREATE ANY PROCEDURE TO DBAMV
/
GRANT CREATE ANY TRIGGER TO DBAMV
/
GRANT CREATE PROCEDURE TO DBAMV
/
GRANT CREATE TRIGGER TO DBAMV
/
GRANT EXECUTE ANY EVALUATION CONTEXT TO DBAMV
/
GRANT EXECUTE ANY PROCEDURE TO DBAMV
/
GRANT EXECUTE ANY PROGRAM TO DBAMV
/
GRANT SELECT ANY TABLE TO DBAMV
/
GRANT ALTER ANY PROCEDURE TO MVINTEGRA
/
GRANT ALTER ANY TRIGGER TO MVINTEGRA
/
GRANT CREATE ANY PROCEDURE TO MVINTEGRA
/
GRANT CREATE ANY TRIGGER TO MVINTEGRA
/
GRANT CREATE PROCEDURE TO MVINTEGRA
/
GRANT CREATE TRIGGER TO MVINTEGRA
/
GRANT EXECUTE ANY EVALUATION CONTEXT TO MVINTEGRA
/
GRANT EXECUTE ANY PROCEDURE TO MVINTEGRA
/
GRANT EXECUTE ANY PROGRAM TO MVINTEGRA
/
GRANT SELECT ANY TABLE TO MVINTEGRA
/
GRANT SELECT ON GV_$SESSION TO DBAMV
/
GRANT SELECT ON GV_$LOCK TO DBAMV
/
-- REFERENTE AO PROBLEMA DE USO DE VIEWS A PARTIR DO 10G RELEASE2
GRANT MERGE ANY VIEW TO DBAMV
/
GRANT EXECUTE ON DBMS_AQ TO DBAMV,DBASGU,MVINTEGRA
/
GRANT EXECUTE ON SYS.DBMS_STANDARD TO DBAMV,DBASGU
/
GRANT EXECUTE ON SYS.STANDARD TO DBAMV,DBASGU
/
GRANT SELECT_CATALOG_ROLE TO DBAMV
/
GRANT SELECT_CATALOG_ROLE TO DBASGU
/
GRANT EXECUTE ON UTL_RECOMP TO DBATUALIZA
/
grant INHERIT PRIVILEGES ON USER system to dbamv 
/
grant INHERIT PRIVILEGES ON USER sys to dbamv 
/
GRANT EXECUTE ON utl_recomp to dbatualiza
/
GRANT EXECUTE ON dbms_crypto TO dbaps
/
GRANT UNLIMITED TABLESPACE TO dbamv WITH ADMIN OPTION
/
GRANT UNLIMITED TABLESPACE TO dbasgu WITH ADMIN OPTION
/

-- HABILITA TRACE
GRANT ALTER SESSION TO MV2000
/

-- DBAPORTAL

GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO DBAPORTAL
/
GRANT SELECT ON sys.dba_jobs TO DBAPORTAL
/

GRANT SELECT,INSERT,DELETE,UPDATE  ON DBASGU.USUARIOS TO DBAMV WITH GRANT OPTION
/


