SELECT PW_DOCUMENTO_CLINICO.CD_DOCUMENTO_CLINICO,'Dt.Sol:'||To_Char(PW_DOCUMENTO_CLINICO.DH_FECHAMENTO,'DD/MM/YYYY HH24:MI')||' '|| Substr(REPLACE(EDITOR_REGISTRO_CAMPO.lo_conteudo, '%20', ' '),InStr(REPLACE(EDITOR_REGISTRO_CAMPO.lo_conteudo,'%20', ' '),'|')+2)
cd_resposta
      ,'N' 
  FROM DBAMV.PW_DOCUMENTO_CLINICO
  JOIN DBAMV.PW_EDITOR_CLINICO
    ON PW_DOCUMENTO_CLINICO.CD_DOCUMENTO_CLINICO = PW_EDITOR_CLINICO.CD_DOCUMENTO_CLINICO
  JOIN editor.EDITOR_REGISTRO_CAMPO 
    ON PW_EDITOR_CLINICO.CD_EDITOR_REGISTRO = EDITOR_REGISTRO_CAMPO.CD_REGISTRO 
  JOIN editor.EDITOR_CAMPO
    ON EDITOR_REGISTRO_CAMPO.CD_CAMPO = EDITOR_CAMPO.CD_CAMPO
  WHERE PW_DOCUMENTO_CLINICO.cd_objeto = 425
    AND PW_DOCUMENTO_CLINICO.TP_STATUS = 'FECHADO'
    AND EDITOR_CAMPO.CD_CAMPO = 4894
    AND PW_DOCUMENTO_CLINICO.CD_PACIENTE = 29

