--<DS_SCRIPT>
-- DESCRICAO..: SCRIPT PARA CONCEDER PERMISSAO A OBJETOS DO MVCPOE
-- RESPONSAVEL: VALBER SILVA
-- DATA.......: 23/02/22
-- PRODUTO....: NOVA PRESCRICAO
--</DS_SCRIPT>
--<USUARIO=DBAMV>


--PERMISSAO OWNER
GRANT CREATE ANY TRIGGER TO MVCPOE
/
--TYPE
GRANT EXECUTE ON DBAMV.TYP_ITPREMED_ESPELHO_OBJ TO MVCPOE
/
GRANT EXECUTE ON DBAMV.ARG_LIST TO MVCPOE
/
GRANT EXECUTE ON DBAMV.TYP_HORARIO_ITEM_OBJ TO MVCPOE
/
--PACKAGE
GRANT EXECUTE ON DBAMV.PKG_XML TO MVCPOE
/
GRANT EXECUTE ON DBAMV.MGES TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PARAMETRO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_XML_MGS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.M_PKG_FFCV_PRO_FAT TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_LANCA_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_CONTA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_FFCV_PROIBICAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_IT_CONTA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_QTD_PROC_ATEND_PAC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_REMESSA_FATURA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_AUX_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_RASTREABILIDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.VAL_PROC_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFIS_VALIDA_LANCAMENTO_AIH TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_FFIS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SUS_REGRA_SETOR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_SUS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SUS_REGRA_PRESTADOR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_LANCA_FFIS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SUS_REGRA_CBO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_NOTA_FISCAL TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKT_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKT_IT_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKT_VAL_OPME_IT_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFCV_TISS_PII TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG$IMPRESSAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_USUARIO_ULT_ACESSO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_MVPEP_PROTOCOLO_CLINICO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SCMA_ONCOLOGIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FSCC_AVISO_CIRURGIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_CENTRAL_MARCACOES TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_AGENDAMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_PAINEL_ONCOLOGIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_CHECAGEM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_M_CONFIG_PAGU_C TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PBSA_M_CANCEL_SOL_C TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PSBA_C_SOLIC_SANGUE_C TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKT_CONFIG_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_APRAZAMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_GERA_SOLICITACAO_PSSD TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_MGES_IMPRIME_SOLSAI_PRO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SUS_REGRA_PROCEDIMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SUS_REGRA_DOCUMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PCK_LCTO_AMB TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PK_SGU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_VALIDA_PERMISSOES TO MVCPOE
/
GRANT EXECUTE ON dbamv.pack_ffcv TO MVCPOE
/




--FUNCAO
GRANT EXECUTE ON DBAMV.FNC_FFCV_PROIBICAO_IDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_ITEM_EVENTO_ADVERSO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_ITEM_TIP_FRE_N_FREQ TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_ITEM_FOR_APL_N_FREQ TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_INTE_DROGA_ALIMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_INTERACAO_DROGA_CID TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_INTE_DROGA_RESUL_EXA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_INTERACAO_DROGA_EXA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_VALIDA_TIPPRESC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_VALIDA_DILUENTE_ITEM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_ULTIMO_HORARIO_ATEND TO MVCPOE
/
GRANT EXECUTE ON DBAMV.Fnc_Mvpep_Item_Alta_Vigilancia TO MVCPOE
/
GRANT EXECUTE ON DBAMV.Fnc_Mvpep_Item_Antimicrobiano TO MVCPOE
/
GRANT EXECUTE ON DBAMV.Fnc_Mvpep_Item_Uso_Restrito TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PEP_BUSCA_TIPO_OBJETO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PEP_BUSCA_COD_TIP_DOC_CLIN TO MVCPOE
/
GRANT EXECUTE ON DBAMV.F_GRAVA_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_FIRST_DAY_SEMANA_BR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_INSERE_REG_FAT TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_INSERE_REG_AMB TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FRANQUIA_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FRANQUIA_CONTA_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_VERIFICA_PRECO_LCTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.VAL_PROC_FFCV_RESUMIDO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_SN_OPME TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_RESTRICAO_SETOR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_RETORNA_PERCENT_CNSG TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFIS_DEFINE_TIPO_VINCULO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_TIPO_GUIA_GRU_FAT TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_VERIFICA_UTILIZ_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_GERA_NUMERO_GUIA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_CONFIRMAR_DIAGNOST TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_CRIAR_PRESCRICAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_CRIAR_PRESCRICAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVSACR_RECUPERA_TRIAGEM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_GRAVA_HORARIO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPAINEL_VERIFICA_PENDEN TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_RETORNA_DSUNIDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_RETORNA_DSUNIDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_RETORNA_DSUNIDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_RETORNA_DSUNIDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_GERA_TISS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_CALCULA_INFUSAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_VALOR_USO_ANTIMICROB TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_VALIDA_TIPPRESC_NOVA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_UNIDADE_PRESCRICAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSIH_VERIFICA_VIGILANCIA TO MVCPOE
/
GRANT EXECUTE ON DBASGU.FNC_MV_PARAMETRO_DEFAULT TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PARI_CANC_ALTA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_CONF_TISS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_RELATORIO_TISS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_LISTAITEMPRESCRICAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_LISTAITEMPRESCRICOES TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_CONSULTARINFRECEITA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_VALIDA_ITENS_PRESC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FN_RETORNA_DIAS_USO_PACIENTE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_SUGESTAO_PROTOCOLO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSIH_INSERIR_MOV_INV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_SESSOES_DIA_PACIENTE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_VERIFICA_CRIAR_HORARIOS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_LEITO_ATENDIMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_INSERE_ATENDIME TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_R_ANTIMICROB_EMPRESA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_R_ANTIMICROB_EMPRESA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_R_ANTIMICROB_EMPRESA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_RETORNA_MATERIAL_SEC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_SEQ_PED_LAB TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_RETORNA_SINAL_VITAL TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSSD_EXIST_EXCECAO_EXAME TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSSD_RETORNA_DT_ENTREGA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_GUIA_IMAGEM_SADT TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSDI_NM_ATUAL_CONTROLE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSDI_RETORNA_DT_ENTREGA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFIS_CHECA_REGRA_SUS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PEP_BUSCA_CODIGO_TIP_DOCUM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PEP_CONFIRMA_CODIGO_USU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PEP_BUSC_CD_PRESTA_USUARIO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PEP_BUSCA_CODIGO_PACIENTE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PROCED_INV_TEMP_RETORNO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_REGISTRA_NOTIFICACAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.LANCA_PAGU_AMB_FFC TO MVCPOE
/


-- PROCEDURE
GRANT EXECUTE ON DBAMV.PRC_FFCV_REPLICA_PROC_HE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PROC_REL_QUEBRA_CONTA_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.LANCA_FFCV_PRO_RELACIONADOS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_GRAVA_LOG_ERRO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFCV_BLOQ_CONTA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFCV_COMPOE_APRES_PRODUTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFCV_AUTOR_AUTO_IPSEMG TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFCV_AUTOR_ATEND_IPSEMG TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_MVPEP_CRIA_AVAL_FARM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PAGU_COPIA_PRESC_PADRAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PISH_AUDITA_ATEND_PRODUTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PSIH_RETORNA_PRE_PAD TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_MVPEP_COPIAR_PRESCRICAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_RETORNA_DOCUMENTOS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PAGU_RETORNA_SET_UNID TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_CANCELA_DIAGNOSTICO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFCV_ALTERA_DT_LANCA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PROCESSA_INDICACAO_PAC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PROCESSA_INDICACAO_PAC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_EXCLUI_REG_ISO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PROCESSA_INDICACAO_PAC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_CONTROLA_ISOLAMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_CONTROLA_ISOLAMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_MVPEP_EXCLUI_PRESC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PAGU_CANCELA_SOLIC_PEND TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PAGU_CANCELA_SOLIC_SANGUE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.VERIF_VL_FATOR_PROD TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PSIH_AUDITA_PRORROGACAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_VERIFICA_RESTRICAO_EXA_LAB TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PSSD_CONFIRMA_EXCECAO_EXAM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_INSERE_LOG_GERA_PSND TO MVCPOE
/
GRANT EXECUTE ON DBAMV.LANCA_FFCV_EQUIPE_PAGU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_CARGA_CORRIGE_DOCS_ORFAOS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFAS_LANCA_PAGU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFAS_LANCA_PAGU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFAS_LANCA_PREMED_APAC_CON TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFAS_LANCA_PREMED_APAC_LAU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_INSERE_APAC_PENDENTE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_LANCA_HIST_AUDIT_PSIH TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_LANCA_PRESC_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_MVPEP_APAGA_DOCS_ORFAOS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFAS_CRITICAS_INTEGRA_APAC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_SACR_CHAMADA_PAINEL_MV TO MVCPOE
/


--SEQUENCE

GRANT SELECT ON DBAMV.TIP_DOC_SEQ TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_TURNO_SETOR TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CONFIG_PAGU_JUSTIFICATIVA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_PW_LOG_PRE_MED TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_LOG_PRE_MED_TRATAMENTO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CONREC TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_ITCON_REC TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_FATURA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_REMESSA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_REG_FAT TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_IT_GUIA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_LOG_FALHA_IMPORTACAO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CONTA_KIT TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_GUIA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_FECHAMENTO_PAGU TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_TRATAMENTO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_SOLIC_AGENDAMENTO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_PW_FAVORITO_CID TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CONFIG_PAGU_PRESCRICAO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_DIAGNOSTICO_ATENDIME TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_ITPRE_MED TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_PRE_MED_TRATAMENTO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_REG_ISO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_SACR_PENDENCIA_SALA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_SACR_PENDENCIA_ORIGEM TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_LOG_EXC_EXA_RX TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_SOLIC_SANGUE TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_IT_SOLIC_SANGUE TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_MOV_INV TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_REG_INF TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_ITPED_LAB TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_PONTO_CURVA_ITPED_LAB TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_PED_RX TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_ITPED_RX TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_MOV_CARDAPIO TO MVCPOE
/
GRANT SELECT ON DBAMV.CTR_FREQUENCIA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_LAUDO_SIA_APAC TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CTR_FREQ TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_AUTORIZACAO_APAC TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CTR_FREQ TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_CTR_FREQ TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_APAC TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_EVENTOS TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_REMESSA_APAC TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_LOG_CITPRE_MED_TRATAMENTO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_LIB_PROD_NPADRONIZADO TO MVCPOE
/



-- TABELA
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PROTOCOLO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_PRE_PAD_SETOR TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PAGU_OBJETO_PARAMETRO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_OBJETO_GRUPO_PRESCRICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITPRE_PAD_FORMULA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_GRUPO_ITEM_PRESCRICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.DIA_ITPRE_PAD TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_FAVORITO_PRESCRICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TIP_ESQ TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TIP_PRESC_PAGU_OBJETO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SUB_GRUPO_PRESCRICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CICLO_TRTM_PROTOCOLO_PREPAD TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_DOCUMENTO_OBJETO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_GRUPO_PRESCRICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_CONFIG_ESQMA_REDUCAO_QUANTD TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBASGU.PARAMETRO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON Dbamv.Pre_Pad TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON Dbamv.itPre_Pad TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBASGU.PARAM_MODULO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_CONFIG_ESQUEMA_OBS_PREDEF TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_CONFIG_PEND_DOC_TIP_DOC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.GRU_ESQ TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.IMPORTACAO_AUTOMATICA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_TIPO_CONSULTA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PAGU_PERGUNTA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ATI_MED TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_FALHA_IMPORTACAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITMVTO_ESTOQUE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.IT_SOLIC_SANGUE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.APARELHOS_EQUIPTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITMOV_CARDAPIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.OPCAO_CARDAPIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITREG_FAT TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITREG_AMB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REG_FAT TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REG_AMB TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CON_PLA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EMPRESA_CONVENIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONVENIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ORI_ATE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ATENDIME TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_FFCV TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.GRU_PRO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRO_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SETOR_GRU_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EMPRESA_CON_PLA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EMPRESA_CONVENIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EMPRESA_CON_PLA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONTA_PACOTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.GUIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.VAL_PRO_RELACIONADO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGRA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIP_DOC_SEQ TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CON_REC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITCON_REC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FATURA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REMESSA_FATURA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITAGRUPAMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CARTEIRA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FRANQUIAS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FRANQUIAS_EXCECAO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITREGRA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITHORARIO_ESPECIAL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITREGRA_EXCECAO_PRO_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITREGRA_EXCECAO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FERIADO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.GRU_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TAB_CONVENIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.HORARIO_ESPECIAL_PROCED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FRANQUIA_VALOR_TOTAL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.VAL_PONTO_FRANQUIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SAL_CIR TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.AVISO_CIRURGIA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PRESTADOR_AVISO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CIRURGIA_AVISO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRES_CON TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_FSCC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRES_CON_EXCECAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.IT_GUIA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PACOTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITLAN_MED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONV_APA_EQPTO_POR_ANE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.AVISO_EQUIPAMENTOS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EMPRESA_APARELHOS_EQUIPTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGRA_GASES_HORAS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGRA_GASES TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.VAL_EXCED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SANGUE_DERIVADOS_PRO_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SANGUE_AVISO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SOLIC_SANGUE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.IT_SOLIC_SANGUE_COMP TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGRA_LIGACAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LAUDO_RX TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FOR_APRE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITFOR_APRE_GRU_PRO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITFOR_APRE_GRU_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROIBICAO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITFOR_APRE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.GABARITO_PRO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.GABARITO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.AUDITORIA_IN_LOCO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.HORARIO_ESPECIAL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TAB_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.POR_ANE_TAB TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SETOR_LANCA_FFCV TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.MVTO_ESTOQUE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIGU_IMPORTACAO_GRU_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRODUTO_ULTIMAS_COMPRAS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITENT_PRO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ENT_PRO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.VAL_OPME_IT_GUIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PERCENTUAL_CONSIGNADO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FORMULA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CONTA_KIT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.FORNECEDOR TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONVENIO_PRO_FAT TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITCOB_PRE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITCOB_PRE_AMBU TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGRA_SUBSTITUICAO_PROCED TO MVCPOE
/
GRANT SELECT,REFERENCES ON DBAMV.MOT_BAI TO MVCPOE
/
GRANT SELECT,REFERENCES ON DBAMV.MOT_DEV TO MVCPOE
/
GRANT SELECT,REFERENCES ON DBAMV.UNIDADE TO MVCPOE
/
GRANT SELECT,REFERENCES ON DBAMV.UNI_PRO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.MOV_CARDAPIO TO MVCPOE
/
GRANT SELECT,REFERENCES ON DBAMV.DEV_PRE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_RX_FORMULA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITFORMULA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITPED_RX_PRODUTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITPED_RX_EQUIPE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.IT_ESCALA_DIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ESCALA_DIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TISS_GUIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.IMPORT_ATEND TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ATENDIME_ORI_MEIO_MAG TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ATENDIME_PROCEDIMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONSUMO_PACIENTE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGRA_ACOPLAMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCEDIMENTO_SUS_PRO_FAT TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITENS_PRESCRICAO_SUS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCEDIMENTO_SUS_INTEGRA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRESTADOR_CBO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ORD_COM TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITCONSUMO_PACIENTE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITLOT_ENT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITORD_PRO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_FFAS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIP_ANEST TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SIPAC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EMPRESA_SIPAC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.COMPAT_PROCEDIMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCEDIMENTO_SUS_VALOR TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.IT_PARTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REGISTRO_CIVIL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCEDIMENTO_CBO_VIGENCIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ADMISSAO_CO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.RECEM_NASCIDO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIPO_VINCULO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.REGISTRO_EVOL_ADMIN TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.AGRUPA_EVOL_ADMIN TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EVOL_ADMIN TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.RES_LEI TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIPO_PENDENCIA TO MVCPOE
/
GRANT SELECT , REFERENCES ON DBAMV.PENDENCIA_ATENDIMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_PARI TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.BALANCO_HIDRICO_FECHAMENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PRESTADORES_IT_GUIA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_ITREG_FAT_REG_LANC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TISS_SOL_GUIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ACOMOD_PRO_FAT TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.FAIXA_GUIA_CONVENIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITEM_FAIXA_GUIA_CONVENIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.IT_AV_PRODUTOS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CAT_PROD TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CAT_PROD_MARCA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TRATAMENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CICLO_TRATAMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SOLIC_ATD TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CIDADE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_DIAGNOSTICO_REALIZADO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROFISSAO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PACIENTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SOLIC_AGENDAMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.IT_AGENDA_CENTRAL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.AGENDA_CENTRAL TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.HRITPRE_MED TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.HRITPRE_CONS TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_FAVORITO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_FAVORITO_CID TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CONFIG_PAGU_ABA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TIP_PRESTA_TIP_ESQ TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PRE_MED_CICLO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.DIAGNOSTICO_CID TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITPRE_MED TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PRE_MED TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PROTOCOLO_DEPENDENCIA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PRE_MED_TRATAMENTO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_PSIH TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.AGE_CIR TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.COLETA_MATERIAL TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SACR_PENDENCIA_ORIGEM TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PW_TIP_PRESC_EVENTO_ADV_PAC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PW_GRAU_EVENTO_ADVERSO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PW_EVENTO_ADVERSO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PW_EVENTO_ADVERSO_PAC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ACAO_PARECER_MEDICO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PAR_MED TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_ENCAMINHAMENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_HISTORICO_ENCAMNH_PAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REGISTRO_RESPOSTA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REGISTRO_DOCUMENTO_IMAGEM TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REGISTRO_DOCUMENTO_OBRIGATORIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REGISTRO_DOCUMENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_DIAGNOSTICO_PACIENTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_CARACT_DIAG_ENFE_PAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_CARACTERISTICA_DIAGNOSTICO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SAE_RESULTADO_ENFERMAGEM TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SAE_INTERVENCAO_ENFERMAGEM TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SAE_RESULTADO_INTERVENCAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SAE_RESULTADO_ENFERMG_RLZD TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SAE_ATIVIDADE_INTERVENCAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_PERG_CONF_HIST_ENFE_SETOR TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_RESP_SELCND_HIST_ENFERMG TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_HISTORICO_ENFERMAGEM TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TRIA_ATND_HIS_IT_COL_SIN_VIT TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SAE_RESP_HISTORICO_ENFERMG TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.COLETA_SINAL_VITAL_AGRUPADA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_OBSERVACAO_PACIENTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_LOG_OBSERVACAO_PACIENTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_RECEITA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_ITEM_RECEITA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PAGU_ITAVALIACAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TRIAG_ATENDIME_HIST_PAGU_AVAL TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PAGU_AVALIACAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.EVO_ENF TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_DOCUMENTO_CLINICO_CONSULTA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_EDITOR_CLINICO_MODULO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_EDITOR_CLINICO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_REGISTRO_ALTA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_ITPRONTUARIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_PRONTUARIO_IMPRESSAO_TEMP TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_PRONTUARIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TRIAG_ATENDIME_HIST_PAGU_AVAL TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_PRONTUARIO_DISTR_LOG_EVENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_TERMO_CONSENTIMENTO_ATND TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_SINAL_SINTOMA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_REGISTRO_OPINIAO_PACIENTE TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_LISTA_EM_ATENDIMENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_HISTORICO_REJEICAO_ATND_PAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_BALANCO_HIDRICO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_PRONTUARIO_DISTR_LOG TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_BALANCO_HIDRICO_FECHAMENTO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_GRUPO_BALANCO_HIDRICO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_ITBALANCO_HIDRICO_FECH TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PW_ITBALANCO_HIDRICO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.MOV_INV TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SACR_PENDENCIA_SALA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITSOLSAI_PRO_ATENDIDO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REMESSA_AMOSTRA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.AMOSTRA_EXA_LAB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.MOV_AMOSTRA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.AMOSTRA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITPED_LAB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PED_LAB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITPED_RX TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PED_RX TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PRESCRICAO_MEDICA_VIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.STATUS_REFEICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_MOV_CARDAPIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.OCORRENCIA_DIETA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.MATERIAL_COLETA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_EXC_PED_LAB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PER_PEDLAB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITPED_USUARIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_EXC_EXA_RX TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_EXC_PED_RX TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PER_PEDRX TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SANGUE_DERIVADOS_COMP TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.HIST_AUDIT_PSIH TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ANTIMICROB TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.TIPO_AUDIT_PSIH TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRO_INV_PSIH TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRO_INVASIVO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REG_INF TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXCECAO_PEDIDO_EXAME TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_LAB_SECUNDARIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_LAB_LABORATORIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.POSTO_COLETA_SETOR TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SETOR_EXECUTANTE_ORI_ATND_EMP TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.MOTIVO_CANCELAMENTO_EXAME TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.SETOR_PRESCRICAO_MULTI_EMPRESA TO MVCPOE
/
GRANT SELECT ON DBAMV.BLOQUEIO_EXAME TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PONTO_CURVA_ITPED_LAB TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_RX_SECUNDARIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CAUGHT_ERRORS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIPO_REFEICAO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_PSND TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIPO_REFEICAO_HORARIO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIPO_DIETA_REFEICAO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.REMESSA_APAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LAUDO_SIA_APAC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCEDIMENTO_SUS_COMPAT_P321 TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CTR_FREQUENCIA TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.AUTORIZACAO_APAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.ITEM_LAUDO_SIA_APAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_FFAS_FALHA_IMPORTACAO_APAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CTR_FREQUENCIA_PROC_SECUNDARIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CTR_FREQUENCIA_PROC_SECUNDARIO TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.EVE_SIASUS TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.APAC TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.FAT_SIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIG_PAGU_PRESCRICAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.UNI_PRESC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITUNIDADE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.UNIDADE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.UNI_PRO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PREMED_TIP_PRESTA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SALA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIP_PRESTA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CIRURGIA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.COMPON TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE , REFERENCES ON DBAMV.COMPON_COMPATIVEL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.COMPON_FILTRO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.CONFIG_PAGU_SETOR TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ESTOQUE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_LAB TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_RX TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.FOR_APL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.HRPAD_SETOR TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.HRTIP_FRE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITEM_AGENDAMENTO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.ITPRE_MED_JUSTIFICATIVA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ITUNIDADE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.LOCAL_ANATOMICO_COLETA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.MATERIAL TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.MULTI_EMPRESAS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PADRAO_FORMULA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRESTADOR TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRO_FAT TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCEDIMENTO_SUS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCESSO_MV TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRODUTO TO MVCPOE
/
GRANT SELECT , REFERENCES ON DBAMV.PW_COMPONENTE_POSOLOGIA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_CONFIG_EXIBICAO_ITEM_PRESC TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_CONFIGURACAO_PADRAO_ITEM TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_CONTROLE_DOSE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PW_DISPOSITIVO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_NOME_EXIBICAO_COMPONENTES TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_OBSERVACAO_PREDEFINIDA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE , REFERENCES ON DBAMV.PW_RESTRICAO_POSOLOGIA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SANGUE_DERIVADOS TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SETOR TO MVCPOE
/
GRANT SELECT , REFERENCES ON DBAMV.TAB_SIASUS TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_FRE TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_FRE_SETOR TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_FRE_TIP_PRESTA_HR_PADRAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_ALERTAS TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_BLOQUEIO_EMPRESA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_DISPOSITIVO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_FOR_APL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_PESQUISA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_SALA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_SETOR TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_SETOR_RESTRITO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE , REFERENCES ON DBAMV.TIP_PRESC_SUBSTITUICAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_TIP_FRE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.TIPO_DIETA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.UNI_PRESC TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.UNI_PRO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.UNIDADE TO MVCPOE
/
GRANT SELECT,REFERENCES ,INSERT, UPDATE, DELETE ON DBAMV.PRE_MED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ATENDIME TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.UNID_INT TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.SOLSAI_PRO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.REGISTRO_CLINICO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_DOCUMENTO_CLINICO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.SESSAO_TRATAMENTO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIPO_SOLICITACAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.SETOR_SET_EXA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.EXA_LAB_SET_EXA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.ITPRE_MED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PRE_USO TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SET_EXA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PAGU_FORMULA TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.PROCESSO_DETALHE_MV TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_GRUPO_PRESCRICAO_ITPRE_MED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CID TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CONFIGURACAO_CURVA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.CITPRE_MED TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_TIPO_DOCUMENTO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.ITPRE_MED_HISTORICO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.ESTADO_PRE_MED TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_AVALIACAO_PRE_MED TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_AVALIACAO_ITPRE_MED TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_AVALIACAO_ITPRE_MED_CONTROL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_PRE_MED_AVALIACAO_STATUS TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.HRITPRE_MED TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.JUSTIFICATIVA_MOBILE TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.FECHAMENTO_PAGU TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_ACAO_COPIA_PRESCRICAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_ACAO_COPIA_ITEM_PRESCRICAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_LOG_ALTERACAO_INFUSAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PW_ITPRE_MED_ALERTA TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.HRITPRE_CONS TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.JUSTIFICATIVA_CHECAGEM TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.HRITSOLSAI_PRO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.ITSOLSAI_PRO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.PRE_PAD_CID TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.CONFIG_ESTOQUE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.ESPECIE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.CLASSE TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SUB_CLAS TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.CONFIG_EXCECAO_ESTOQUE_SUBST TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.MVTO_GASES  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBASGU.USUARIOS  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.IDENTIFICADOR_ETIQUETA  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PW_TEMA_CLINICO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PREMED_TIP_PRESTA_TIP_FRE  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PW_LISTA_PARAMETRO_PAGU_OBJ  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.CONFIG_PAGU TO MVCPOE
/
GRANT DELETE,INSERT, SELECT,UPDATE, REFERENCES ON DBAMV.HRITPRE_VOL  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.RMI_MENSAGEM  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.MEDICAMENTO_PREPARADO_CHECG  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LOG_CITPRE_MED_TRATAMENTO  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.PAINEL_ATENDIMENTO  TO MVCPOE
/ 
GRANT SELECT, REFERENCES ON DBAMV.PRO_FAT_ALTO_CUSTO  TO MVCPOE
/
GRANT SELECT, REFERENCES ON DBAMV.SACR_TEMPO_PROCESSO  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.LIB_PROD_NPADRONIZADO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PW_TIPO_DOCUMENTO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PAGU_OBJETO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CONFIG_PAGU_SETOR  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CONFIG_PAGU  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CONFIG_PAGU_IMPRESSAO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CONFIG_PAGU_JUSTIFICATIVA  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CONFIG_PAGU_PRESCRICAO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CONFIG_PAGU_TRANSF_LEITO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PW_FAVORITO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.TURNO_SETOR  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PREMED_TIP_PRESTA  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PREMED_TIP_PRESTA_TIP_FRE  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON DBAMV.TIP_PRESC_PAD_SETOR TO MVCPOE
/
GRANT SELECT,INSERT, UPDATE,DELETE,REFERENCES ON DBAMV.PW_CONFIG_ITENS_REDUCAO_QUANTD  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT,UPDATE, REFERENCES ON DBAMV.CICLO_TRATAMENTO_PROTOCOLO  TO MVCPOE
/
GRANT DELETE,INSERT,SELECT, UPDATE, REFERENCES ON DBAMV.CITPRE_PAD TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_RETORNA_TURNO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_OBTER_DS_SERVICO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_MV2000 TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSIH_PACIENTE_ISOLADO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_INTER_CRIT_RET_CIRUR_PAC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_GRAVA_CRITERIOS_PESQUISA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.F_PROIBE_MOVIMENTACAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PSIH_VALIDA_PRESCRIC_ANTM TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_DADOS_BLOQUEIO_EXA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_RETORNA_COTA_SETOR_ESTOQUE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.BUSCA_ESTOQUE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.VERIF_LICENCA_PRESTADOR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_HOCA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_FFCV_PROCEDIMENTO_AC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSIH_VERIFC_ANTM_USO_REST TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_RETORNA_TIPO_USO_ANTM   TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PAGU_ATUALIZA_PREVIS_ALTA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_PAGU_VALIDA_PREVIS_ALTA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MVPEP_DELIMITA_STRING TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_MVPEP_CALCULA_FORMULA_PAD TO MVCPOE
/
GRANT EXECUTE ON MVINTEGRA.PKG_IMV_SAIDA_SOLIC_HEMO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.F_RETORNA_FERIADO TO MVCPOE
/
GRANT EXECUTE ON MVINTEGRA.PKG_IMVW_SAI_SOLIC_HEMO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_FFAS_REGRA_FATURA TO MVCPOE
/
GRANT EXECUTE ON MVINTEGRA.PKG_MVINTEGRA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_SUS_REGRA_SERVICO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FN_IDADE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_FFAS_CONTROLA_SUS_TETO_UPS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_RMI_TRADUCAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_CLASSE_RISCO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.LANCA_PAGU_AMB_FFC TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_MV_VARIAVEIS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_TRATAMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_ITPREMED TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_DIAGNOSTICO_ATENDIME TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_LANCA_FFCV TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_RMI_TRADUCAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKT_CONFIG_FFIS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_AVALIACAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PERGUNTA_DOSE_PADRAO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_MV_RECUPERA_DATA_HORA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PRC_RETOR_UNID_SETOR_PACIENTE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKT_CONFIG_FFAS TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_CLASSIFICACAO_RISCO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PAGU_DOCUMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PKG_PSIH_BACTERIA_MTRESISTENTE TO MVCPOE
/
GRANT EXECUTE ON DBAMV.TYPEMVPEPTABVARCHAR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.BUSCA_SET_EXA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PAGU_SETOR_ATENDIMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSIH_VERIF_VIGIL_RESTRITA TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSSD_GET_OBRIGA_CID TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSSD_MATERIAL_COMPLEMENTAR TO MVCPOE
/
GRANT EXECUTE ON DBAMV.PACK_INTERNAMENTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_RETORNA_MATERIAL_SEC TO MVCPOE
/
GRANT SELECT ON DBAMV.EMPRESA_PRODUTO TO MVCPOE
/
GRANT EXECUTE ON DBAMV.FNC_PSSD_RG_CID_PRINCIPAL TO MVCPOE
/
GRANT SELECT ON DBAMV.LIGACAO_PACIENTE TO MVCPOE
/
GRANT SELECT ON DBAMV.CONTA_PACOTE TO MVCPOE
/
GRANT SELECT ON DBAMV.CONFIG_HOCA TO MVCPOE
/
GRANT SELECT, UPDATE  ON DBAMV.CONTA_PACOTE TO MVCPOE
/
GRANT SELECT, INSERT  ON DBAMV.CONTA_PACOTE TO MVCPOE
/
GRANT SELECT, INSERT,DELETE  ON DBAMV.ITCON_REC TO MVCPOE
/
GRANT SELECT, INSERT,DELETE  ON DBAMV.CON_REC TO MVCPOE
/
GRANT SELECT   ON DBAMV.CONFIGURACAO TO MVCPOE
/
GRANT SELECT   ON DBAMV.HOSPITAL TO MVCPOE
/
GRANT SELECT   ON DBAMV.DIAGNOSTICO TO MVCPOE
/
GRANT SELECT   ON DBAMV.TUSS TO MVCPOE
/
GRANT SELECT   ON DBAMV.SER_DIS TO MVCPOE
/
GRANT SELECT   ON DBAMV.SERVICO TO MVCPOE
/
GRANT SELECT   ON DBAMV.PROCEDIMENTO_DETALHE_VIGENCIA TO MVCPOE
/
GRANT SELECT   ON DBAMV.PAGU_ITFORMULA TO MVCPOE
/
GRANT SELECT   ON DBAMV.PAGU_ACAO TO MVCPOE
/
GRANT SELECT   ON DBAMV.COLETA_SINAL_VITAL TO MVCPOE
/
GRANT SELECT   ON DBAMV.PRE_MED_RESPOSTA_FORMULA TO MVCPOE
/
GRANT SELECT   ON DBAMV.PAGU_RESPOSTA TO MVCPOE
/
GRANT SELECT   ON DBAMV.ITCOLETA_SINAL_VITAL TO MVCPOE
/
GRANT SELECT   ON DBAMV.SINAL_VITAL TO MVCPOE
/
GRANT SELECT   ON DBAMV.MOV_CC_RPA TO MVCPOE
/
GRANT SELECT   ON DBAMV.DOCUMENTO TO MVCPOE
/
GRANT SELECT   ON DBAMV.BALANCO_HIDRICO TO MVCPOE
/
GRANT SELECT   ON DBAMV.SUBS_PAC TO MVCPOE
/
GRANT SELECT   ON DBAMV.CONFIG_FFIS TO MVCPOE
/
GRANT SELECT   ON DBAMV.LABORATOR TO MVCPOE
/
GRANT SELECT   ON DBAMV.ESP_MED TO MVCPOE
/
GRANT SELECT   ON DBAMV.CONFIGURACAO_TIPO_PRESCRIC_SET TO MVCPOE
/
GRANT SELECT   ON DBAMV.MOV_INT TO MVCPOE
/
GRANT SELECT   ON DBAMV.LEITO TO MVCPOE
/
GRANT SELECT   ON DBAMV.DIAGNOSTICO_ATENDIME_PROTOCOLO TO MVCPOE
/
GRANT SELECT   ON DBAMV.DIAGNOSTICO_ATENDIME TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE,DELETE   ON DBAMV.DIAGNOSTICO_ATENDIME TO MVCPOE
/
GRANT SELECT   ON DBAMV.ANT_PRO TO MVCPOE
/
GRANT SELECT   ON DBAMV.REGRA_TP_AUDIT_PSIH TO MVCPOE
/
GRANT SELECT   ON DBAMV.ATENDIME_ANT_PRO TO MVCPOE
/
GRANT SELECT   ON DBAMV.CONFIG_NOTIFICACAO TO MVCPOE
/
GRANT SELECT   ON DBAMV.MVPEP_CONFIG_NOTIFICACAO  TO MVCPOE
/
GRANT SELECT   ON DBAMV.PW_NOTIF_VALOR_PARAM_FORMA_ENV  TO MVCPOE
/
GRANT SELECT   ON DBAMV.PW_NOTIF_PARAM_FORMA_ENVIO TO MVCPOE
/
GRANT SELECT   ON DBAMV.PW_NOTIFICACAO_FORMA_ENVIO TO MVCPOE
/
GRANT SELECT   ON DBAMV.PW_FORMA_ENVIO_PARAM_VALOR TO MVCPOE
/
GRANT SELECT   ON DBAMV.SEQ_NOTIFICACAO TO MVCPOE
/
GRANT SELECT,INSERT,UPDATE   ON DBAMV.NOTIFICACAO TO MVCPOE
/
GRANT SELECT,INSERT   ON  DBAMV.MVPEP_NOTIFICACAO TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_CASO_PROTOCOLO TO MVCPOE
/
GRANT SELECT,UPDATE   ON DBAMV.PW_ETAPAS_ALERTA_PROTOCOLO TO MVCPOE
/
GRANT SELECT, UPDATE   ON DBAMV.PW_ETAPA_PROTOCOLO TO MVCPOE
/
GRANT SELECT, UPDATE, INSERT   ON DBAMV.PW_CASO_PROTOCOLO TO MVCPOE
/
GRANT SELECT   ON  DBAMV.SEQ_PW_EVOLUCAO_CASO_PROTOCOLO TO MVCPOE
/
GRANT SELECT, INSERT,UPDATE   ON  DBAMV.PW_EVOLUCAO_CASO_PROTOCOLO TO MVCPOE
/
GRANT SELECT   ON  DBAMV.SEQ_PW_CASO_PROTOCOLO  TO MVCPOE
/
GRANT SELECT   ON  DBAMV.SEQ_PW_CASO_PROTOCOLO_CRITERIO  TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_TIPO_CRITERIO  TO MVCPOE
/
GRANT SELECT, DELETE   ON  DBAMV.PW_CASO_PROTOCOLO_CRITERIO  TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_CRITERIO  TO MVCPOE
/
GRANT SELECT   ON  DBAMV. PW_CASO_PROTOCOLO_CRITERIO  TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_GRUPO_CRITERIO  TO MVCPOE
/
GRANT SELECT   ON   DBAMV.ESPECIALID    TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_CONFIG_ITEM_ALIMENTO    TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_ITCONFIG_RESUL_EXAME_PRESC    TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_CONFIG_RESUL_EXAME_PRESC    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.VAL_REFERENCIA    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.VAL_EXA    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.RES_EXA    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_ITCONFIG_INTER_CID_PRESC    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_CONFIG_INTER_CID_PRESC    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_ITCONFIG_SOLIC_EXAME_DIMIN    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_CONFIG_SOLIC_EXAME_PRESC    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_ITCONFIG_SOLIC_EXAME_ELEV    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_PROBLEMA    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.TRIAGEM_ATENDIMENTO    TO MVCPOE
/
GRANT SELECT   ON  DBAMV.PW_CRITERIO_VALOR_PAR_CONSULT    TO MVCPOE
/
GRANT SELECT   ON   DBAMV.CONSELHO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_TIPO_CRITERIO_PARAM_CONSULT   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_UNIDADE_AFERICAO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.SNOMEDCT_PACIENTE   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.EDITOR_CAMPO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PAGU_OBJETO_PERG_FORMULA   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.TIP_ACOM   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.EDITOR_REGISTRO_CAMPO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.VERSAO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.CULTURA   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.VAL_ECOCARDIO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.EDITOR_REGISTRO   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PW_UNIDADE_FORMULA   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.PAGU_FORMULA_SETOR   TO MVCPOE
/
GRANT SELECT   ON   DBAMV.SEQ_ACAO_TERA   TO MVCPOE
/
GRANT SELECT, INSERT   ON   DBAMV.ACAO_TERA   TO MVCPOE
/
GRANT SELECT  ON   DBAMV.EXA_LAB_MATERIAL    TO MVCPOE
/
GRANT SELECT  ON   DBAMV.CONFIG_PSSD    TO MVCPOE
/
GRANT SELECT  ON   DBAMV.CONFIG_PSDI    TO MVCPOE
/
GRANT SELECT  ON  DBAMV.SEQ_HIST_AUDIT_PSIH TO MVCPOE
/
GRANT SELECT, INSERT,UPDATE,DELETE  ON  DBAMV.HIST_AUDIT_PSIH TO MVCPOE
/
GRANT SELECT  ON  DBAMV.TIPO_AUDITORIA_ISOLAMENTO TO MVCPOE
/
GRANT SELECT,INSERT,UPDATE, DELETE  ON  DBAMV.REG_ISO TO MVCPOE
/
GRANT SELECT,INSERT,UPDATE, DELETE  ON  DBAMV.PW_INDICACAO_PACIENTE TO MVCPOE
/
GRANT SELECT  ON  DBAMV.MULTI_EMPRESAS_CBO TO MVCPOE
/
GRANT SELECT  ON  DBAMV.TIP_MAR TO MVCPOE
/
GRANT SELECT ON DBAMV.SUBSTANCIA TO MVCPOE
/
GRANT SELECT ON DBAMV.PW_ALERGIA_PAC TO MVCPOE
/
GRANT SELECT ON DBAMV.PRO_GRUTRA TO MVCPOE
/
GRANT SELECT ON DBAMV.PREST_GRU_PRO_PROIBIDO TO MVCPOE
/
GRANT SELECT ON DBAMV.CONFIGEST TO MVCPOE
/
GRANT EXECUTE ON DBAMV.VALIDA_DADOS_PRESTADOR TO MVCPOE
/
GRANT SELECT ON DBAMV.ITPAL_CHA TO MVCPOE
/
GRANT SELECT ON DBAMV.ACA_PRO TO MVCPOE
/
GRANT SELECT ON DBAMV.LAB_PRO TO MVCPOE
/
GRANT SELECT ON DBAMV.SUBS_PRO TO MVCPOE
/
GRANT SELECT ON DBAMV.GRU_TRA TO MVCPOE
/
GRANT SELECT ON DBAMV.IMPORT_ATEND_PRO_FAT TO MVCPOE
/
GRANT SELECT, DELETE, INSERT, UPDATE ON DBAMV.ACAO_PARECER_MEDICO TO MVCPOE
/
GRANT SELECT ON DBAMV.DOCUMENTO_OBRIGATORIO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_PW_DOCUMENTO_CLINICO TO MVCPOE
/
GRANT SELECT, UPDATE, INSERT, DELETE ON DBAMV.NOTIFICACAO  TO MVCPOE
/
GRANT SELECT, UPDATE, INSERT, DELETE ON DBAMV.SANGUE_AVISO  TO MVCPOE
/
GRANT SELECT, UPDATE, INSERT, DELETE ON DBAMV.IT_AGENDA_CENTRAL  TO MVCPOE
/
GRANT SELECT, UPDATE, INSERT, DELETE ON DBAMV.AGENDA_CENTRAL  TO MVCPOE
/
GRANT SELECT ON MVINTEGRA.CONFIG_MVINTEGRA TO MVCPOE
/
GRANT SELECT, DELETE, UPDATE, INSERT ON DBAMV.IDENTIFICADOR_ETIQUETA_CHECG TO MVCPOE
/
GRANT SELECT,INSERT, UPDATE, DELETE ON MVINTEGRA.INTEGRA_SAIDA_HEMODERIVADO TO MVCPOE
/
GRANT SELECT ON MVINTEGRA.SEQ_INTEGRA_SAIDA_HEMODERIVADO TO MVCPOE
/
GRANT SELECT ON MVINTEGRA.SEQ_IMV_HEMODERIVADO TO MVCPOE
/
GRANT SELECT,INSERT, UPDATE, DELETE ON MVINTEGRA.IMV_HEMODERIVADO TO MVCPOE
/
GRANT SELECT ON DBAMV.TAB_SSM_APAC TO MVCPOE
/
GRANT SELECT,INSERT, UPDATE, DELETE ON DBAMV.APAC_PENDENTE TO MVCPOE
/
GRANT SELECT,INSERT, UPDATE, DELETE ON DBAMV.LOG_DOC_ORFAO_PACIENTE TO MVCPOE
/
GRANT SELECT ON DBAMV.PADRAO_FORMULA_PERGUNTA TO MVCPOE
/
GRANT SELECT ON DBAMV.EXA_SET TO MVCPOE
/
GRANT SELECT ON DBAMV.SET_EXA_PADRAO TO MVCPOE
/
GRANT SELECT ON DBAMV.SET_EXA_PADRAO_HOR_ESP TO MVCPOE
/
GRANT SELECT ON DBAMV.LOG_GERACAO_MAPA TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_SOLSAI_PRO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_ITSOLSAI_PRO TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_MVTO_GASES TO MVCPOE
/
GRANT SELECT ON DBAMV.ITEM_PRECAUCAO TO MVCPOE
/
GRANT SELECT ON DBAMV.EST_PRO TO MVCPOE
/
GRANT SELECT ON DBAMV.SUBS_INTERACAO TO MVCPOE
/

GRANT SELECT ON DBAMV.ATENDIMENTO_TIPO_AUDIT_ISOLAMT TO MVCPOE
/
GRANT SELECT ON DBAMV.REGRA_TIPO_AUDITORIA_ISOLAMT TO MVCPOE
/
GRANT SELECT, INSERT, DELETE, UPDATE ON ITSOLSAI_PRO_FECHAMENTO TO MVCPOE
/
GRANT SELECT, INSERT, DELETE, UPDATE ON DBAMV.CONFIG_PBSA TO MVCPOE
/
GRANT SELECT, UPDATE ON ATENDIME TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON DBAMV.SOLICITACAO_TRATAMTO_PRO_AVUL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON DBAMV.ITCOLETA_SINAL_VITAL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON DBAMV.COLETA_SINAL_VITAL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE  ON DBAMV.COLETA_SINAL_VITAL TO MVCPOE
/
GRANT SELECT ON DBAMV.SEQ_COLETA_SINAL_VITAL TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON DBAMV.FRACIONAMENTO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.IMPRESSAO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.IMP_PARAMETRO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.PITPRE_MED TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.NAO_CONFORMIDADE TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.BALANCO_HIDRICO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.MVPEP_NOTIFICACAO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.AVISO_RECOLETA TO MVCPOE
/
GRANT SELECT  ON DBASGU.SEQ_PARAM_MODULO_VALOR TO MVCPOE
/
GRANT INSERT  ON DBASGU.PARAM_MODULO_VALOR TO MVCPOE
/
GRANT SELECT   ON DBAMV.CONFIGURACAO_ASSINATURA_DIGIT TO MVCPOE
/
GRANT SELECT   ON DBAMV.SEQ_CONFIGURACAO_ASSINAT_DIGIT TO MVCPOE
/
GRANT SELECT   ON DBAMV.TIPO_REPOSITORIO TO MVCPOE
/
GRANT SELECT   ON DBAMV.PW_EMPRESA_EXTERNA TO MVCPOE
/
GRANT EXECUTE   ON DBAMV.FNC_MVPEP_RETORNA_TP_SETOR TO MVCPOE
/
GRANT SELECT, REFERENCES   ON DBAMV.TIP_RES TO MVCPOE
/
GRANT EXECUTE   ON DBAMV.FN_IDADE_PACIENTE TO MVCPOE
/
GRANT EXECUTE   ON DBAMV.PKT_CONVENIO TO MVCPOE
/
GRANT SELECT    ON DBAMV.EXA_LAB_LOCAL_ANATOMICO_COLETA TO MVCPOE
/
GRANT SELECT    ON DBAMV.PRESTADOR_ASSINATURA TO MVCPOE
/
GRANT SELECT    ON DBAMV.PW_DOC_ALERGIA_PAC TO MVCPOE
/
GRANT EXECUTE    ON DBAMV.FNC_MVPEP_DOSE_PADRAO_ITEM_ALT TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.ALTERACAO_ITPRE_MED TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.PW_FECHAMENTO_HORARIO_CHECAGEM TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.PW_HRITPRE_MED_PRESCRICAO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.HORA_COMPONT_IT_PRESCRIC_CSMD TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.PW_HORARIO_FECHADO_CHECAGEM TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.HRITPRE_MED_PREPARO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.HR_CPNT_IT_PRESC_CSMD_DP_CHEC TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.HRITPRE_CONS_DUPLA_CHECAGEM TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.ITPRE_MED_PONTO_CURVA TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT  ON DBAMV.LOG_PRESCRICAO TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.CAUGHT_ERRORS  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PRE_MED_RESPOSTA_FORMULA  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.LOG_PRE_MED_TRATAMENTO  TO MVCPOE
/
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES  ON DBAMV.PW_LOG_PRE_MED  TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.TIP_ESQ_EXCECAO TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.FOR_APL TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.HRPAD_SETOR TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.TIP_FRE_SETOR TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.HRTIP_FRE TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.TIP_FRE TO MVCPOE
/
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMV.TIP_FRE_TIP_PRESTA_HR_PADRAO TO MVCPOE
/
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON dbamv.pw_parametro_pagu_objeto TO mvcpoe
/
GRANT SELECT ON dbamv.seq_pre_pad TO mvcpoe
/
GRANT SELECT ON dbamv.seq_itpre_pad TO mvcpoe
/
GRANT SELECT ON dbamv.copa TO mvcpoe
/
GRANT  DELETE, INSERT, REFERENCES, SELECT, UPDATE ON dbamv.pw_grupo_prescricao_tipo_esqm TO mvcpoe
/
GRANT EXECUTE ON  DBAMV.PKG_MVPEP_WRAPPER  TO mvcpoe
/
GRANT SELECT ON  dbamv.sacr_classificacao  TO mvcpoe
/
GRANT EXECUTE ON dbamv.fnc_mvpep_valida_itpre_med TO mvcpoe
/
GRANT EXECUTE ON MVCPOE.FNC_PAGU_DESCRICAO_ITEM TO dbamv
/
GRANT EXECUTE ON MVCPOE.FNC_PAGU_DESCRICAO_ITEM TO mv2000
/