SELECT PRESTADOR.NM_PRESTADOR
      ,REGISTRO_PLANTAO.DT_INICIO 
      ,REGISTRO_PLANTAO.DT_FIM
      ,SETOR.NM_SETOR
      ,round(to_number(REGISTRO_PLANTAO.DT_FIM - REGISTRO_PLANTAO.DT_INICIO))||' Dia(s) '||
      Trunc(Mod((((to_number(REGISTRO_PLANTAO.DT_FIM - REGISTRO_PLANTAO.DT_INICIO)) * 1440)/60),24))||' Hora(s) '||
      Trunc(Mod(((to_number(REGISTRO_PLANTAO.DT_FIM - REGISTRO_PLANTAO.DT_INICIO) * 1440)),60))||' Minuto(s)' ||
      round(Mod(((to_number(REGISTRO_PLANTAO.DT_FIM - REGISTRO_PLANTAO.DT_INICIO) * 1440)*60),60))||' Segundos(s)' intervalo
  FROM DBAMV.REGISTRO_PLANTAO
  JOIN DBAMV.PRESTADOR
    ON REGISTRO_PLANTAO.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
  JOIN SETOR
    ON REGISTRO_PLANTAO.CD_SETOR = SETOR.CD_SETOR
  WHERE REGISTRO_PLANTAO.DT_FIM IS NOT NULL
