SELECT PRE_MED.CD_ATENDIMENTO 
      ,TIP_PRESC.DS_TIP_PRESC
      ,TIP_FRE.DS_TIP_FRE
      ,PRE_MED.DT_VALIDADE
      ,PRE_MED.DH_IMPRESSAO 
  FROM DBAMV.PRE_MED
  JOIN DBAMV.ITPRE_MED
    ON PRE_MED.CD_PRE_MED = ITPRE_MED.CD_PRE_MED 
  JOIN DBAMV.TIP_PRESC
    ON ITPRE_MED.CD_TIP_PRESC = TIP_PRESC.CD_TIP_PRESC
  JOIN DBAMV.TIP_FRE
    ON ITPRE_MED.CD_TIP_FRE = TIP_FRE.CD_TIP_FRE
  WHERE ITPRE_MED.CD_TIP_FRE IN (26,109)
    AND DT_PRE_MED = '17/11/2022'
