SELECT  PACIENTE.NM_PACIENTE
       ,TIP_PRESC.DS_TIP_PRESC
      ,PW_EVENTO_ADVERSO.DS_EVENTO_ADVERSO
      ,CASE
            WHEN PW_GRAU_EVENTO_ADVERSO.TP_GRAU_EVENTO_ADVERSO = 'ML' THEN 'Muy leve'
            WHEN PW_GRAU_EVENTO_ADVERSO.TP_GRAU_EVENTO_ADVERSO = 'LV' THEN 'Leve'
            WHEN PW_GRAU_EVENTO_ADVERSO.TP_GRAU_EVENTO_ADVERSO = 'MD' THEN 'Moderado'
            WHEN PW_GRAU_EVENTO_ADVERSO.TP_GRAU_EVENTO_ADVERSO = 'GR' THEN 'Grave'
            WHEN PW_GRAU_EVENTO_ADVERSO.TP_GRAU_EVENTO_ADVERSO = 'RM' THEN 'Risgo de Muerte'
            WHEN PW_GRAU_EVENTO_ADVERSO.TP_GRAU_EVENTO_ADVERSO = 'MR' THEN 'Muerte'
        ELSE NULL
        END TP_GRAU_EVENTO_ADVERSO
      ,To_Char(PW_EVENTO_ADVERSO_PAC.DH_CRIACAO,'dd/mm/rrrr hh24:mi')|| ' por: '|| PRESTADOR.NM_PRESTADOR      DH_CRIACAO
      ,To_Char(PW_EVENTO_ADVERSO_PAC.dh_modificacao,'dd/mm/rrrr hh24:mi') DH_MODIFICACAO
      ,Decode (PW_EVENTO_ADVERSO_PAC.SN_ATIVO,'S','Activo','Inactivo')    SN_ATIVO
      ,PW_EVENTO_ADVERSO_PAC.DS_JUSTIFICATIVA_INATIVACAO
  FROM DBAMV.PW_EVENTO_ADVERSO_PAC
  JOIN DBAMV.PACIENTE
    ON PW_EVENTO_ADVERSO_PAC.CD_PACIENTE = PACIENTE.CD_PACIENTE
  JOIN dbamv.prestador
    ON PW_EVENTO_ADVERSO_PAC.CD_PRESTADOR_CRIACAO = PRESTADOR.CD_PRESTADOR
  JOIN DBAMV.PW_PROBLEMA
    ON PW_EVENTO_ADVERSO_PAC.CD_PROBLEMA = PW_PROBLEMA.CD_PROBLEMA
  JOIN DBAMV.PW_EVENTO_ADVERSO
    ON PW_EVENTO_ADVERSO_PAC.CD_EVENTO_ADVERSO = PW_EVENTO_ADVERSO.CD_EVENTO_ADVERSO
  JOIN DBAMV.PW_TIP_PRESC_EVENTO_ADV_PAC
    ON PW_PROBLEMA.CD_PROBLEMA = PW_TIP_PRESC_EVENTO_ADV_PAC.CD_PROBLEMA
  JOIN DBAMV.TIP_PRESC
    ON TIP_PRESC.CD_TIP_PRESC = PW_TIP_PRESC_EVENTO_ADV_PAC.CD_TIP_PRESC
  JOIN DBAMV.PW_GRAU_EVENTO_ADVERSO
    ON PW_EVENTO_ADVERSO_PAC.CD_GRAU_EVENTO_ADVERSO = PW_GRAU_EVENTO_ADVERSO.CD_GRAU_EVENTO_ADVERSO
  WHERE PW_EVENTO_ADVERSO_PAC.CD_PACIENTE  = 4
